version: "3.9"

networks:
  backend:
    external: false

services:
  api:
    container_name: rrhh-back
    image: "teleback:1.0.1"
    networks:
      - backend
    environment:
      POSTGRES_USER: prueba
      POSTGRES_PASSWORD: prueba
      POSTGRES_DB: prueba
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PUBLIC_IP: 0.0.0.0
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/code
  db:
    container_name: postgres-db
    image: postgres:15.1-alpine3.16
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_USER: prueba
      POSTGRES_PASSWORD: prueba
      POSTGRES_DB: prueba
