version: "3.9"

volumes:
  pgdata:

networks:
  backend:
    name: backend
    external: false
  frontend:
    name: frontend
    external: true

services:
  api:
    container_name: rrhh-back
    image: "epava1516/teleback:1.0.0"
    networks:
      - backend
      - frontend
    environment:
      POSTGRES_USER: prueba
      POSTGRES_PASSWORD: prueba
      POSTGRES_DB: prueba
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PUBLIC_IP: 0.0.0.0
      DJANGO_DEBUG: 1
      DJANGO_SECRET_KEY: prueba
      ALLOWED_EXTERNAL: '192.168.1.243,api,localhost,127.0.0.1'
    restart: unless-stopped
    ports:
      - "80:8000"
    volumes:
      - .:/code
  db:
    container_name: postgres-db
    image: postgres:15.1-alpine3.16
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_USER: prueba
      POSTGRES_PASSWORD: prueba
      POSTGRES_DB: prueba
    volumes:
      - pgdata:/var/lib/postgresql/data