# Generated by Django 4.1.3 on 2022-11-21 07:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=30, null=True)),
                ('coordinates', models.JSONField(null=True)),
                ('addressCity', models.CharField(max_length=30)),
                ('addressCountry', models.CharField(max_length=30)),
                ('addressPostalcode', models.CharField(max_length=30, null=True)),
                ('addressState', models.CharField(max_length=30)),
                ('addressStreet', models.CharField(max_length=30, null=True)),
                ('services', models.JSONField(null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30, null=True)),
                ('lastName', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('galeryPath', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(max_length=30, null=True)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('genre', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=30)),
                ('nationality', models.CharField(choices=[('ES', 'Española'), ('FR', 'Francesa')], max_length=30, null=True)),
                ('phone_prefix', models.IntegerField(null=True)),
                ('phone', models.IntegerField()),
                ('show_phone', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('show_email', models.BooleanField(default=False)),
                ('dni', models.CharField(max_length=30, null=True, unique=True)),
                ('dniPhoto', models.CharField(max_length=30, null=True, unique=True)),
                ('coordinates', models.JSONField(null=True)),
                ('addressCity', models.CharField(max_length=30)),
                ('addressCountry', models.CharField(max_length=30)),
                ('addressPostalcode', models.CharField(max_length=30, null=True)),
                ('addressState', models.CharField(max_length=30)),
                ('addressZone', models.CharField(max_length=30, null=True)),
                ('addressStreet', models.CharField(max_length=30, null=True)),
                ('services', models.JSONField(null=True)),
                ('isWorker', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(default=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=50)),
                ('checksum', models.CharField(max_length=50, unique=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(max_length=30, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='api.user')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=50)),
                ('checksum', models.CharField(max_length=50, unique=True)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(max_length=30, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Grupo', to='api.user')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
